### PR TITLE
Exam fixes

### PR DESCRIPTION
**Pull request by ksungreborn**
See https://github.com/attendanceproject/djattendance/issues/979 for what needed to be accomplished in this pull request. Once we merge, Raizel can start making exams for midterms (hopefully everything looks good).

### CODE REVIEW

**Comment by iamsitting** [comment]
Exams to do
1. Trainee can see graded exam after finalizing exam (not sure if this is intentional).
2. "Study Roll" shows up as an option for training class
3. Looks good.
4. Looks good.
5. I enter a score for a trainee. Neither the table nor nor exam overview shows that. Maybe also make the table a data-table so the TA can just search for the trainee
6. Points field does not accept float (requires an integer)
7. Looks good. Maybe validate so value maxes out at number of questions
8. Looks good.
9. Looks good.

More problems:
1. It seems that every time I caused an error while making an exam, a new exam was being created (seen in the exam manager page). It's not super-critical because they can be deleted, but still needs to be resolved.

**Comment by ksungreborn** [comment]
1. I think the purpose is that trainees can see the autograded questions right away. But let me check with Raizel
2. Fixed
5. It looks good on my branch. Made this table a data-table.
6. Fixed

More problems:
1. Yes, I will take a look at this later. I agree it is important

**Comment by ksungreborn** [comment]
Added two fixes:
1. Filter exams shown for 2nd and 1st year trainees
2. Do not show graded exam after trainee finalizes exam

**Comment by billyeh** [comment]
http://ap.ftta.lan/admin/classes/class/

**Comment by ruthnan** [comment]
@billyeh, so leave it on the "Current" tab for now, and move the other apps under there (like Grad and Intentions forms) later?

**Comment by billyeh** [comment]
That's a UI/TA question 😁

**Pull request merged**
