### PR TITLE
hc survey frontend changes

### PR DESCRIPTION
**Pull request by yipingbenjaminliu**

### CODE REVIEW

**Comment by yipingbenjaminliu** [comment]
@francestsenn , could you fix up the front end so it's more intuitional and functional? mainly just a showall/collapseall button. a search input for house or trainee would be nice too

**Comment by iamsitting** [comment]
What issue or problem is this PR addressing? (Can't review if I don't know what it's suppose to fix)

**Comment by yipingbenjaminliu** [comment]
it's not really a fix, it's just a front end change...

**Comment by yipingbenjaminliu** [comment]
okay, i'm merging it.

**Pull request merged**
