### PR TITLE
update absent trainee roster

### PR DESCRIPTION
**Pull request by poohbear0628**
notifications about not doing the absent trainee roster on Sundays and Mondays won't show up again after the update

### CODE REVIEW

**Comment by bdou** [comment]
Hi Serena! One note: HCs are still required to put in house attendance on Sundays.

**Comment by poohbear0628** [comment]
@bdou okay! just made the change to the code. Has will still receive the notifications on Sundays butn not on Mondays.

**Comment by JoannaRumbley** [comment]
When will the change be made on the live server? It still showed the notification today for Monday

**Comment by ryanli633** [comment]
I deployed the change on the live server on Saturday. So, it should have worked for this Monday. I didn't really look through the code in detail though. @poohbear0628 , could you double check to make sure the alert doesn't show on Mondays?

**Pull request merged**
