### PR TITLE
1381/rr doublebookfix

### PR DESCRIPTION
**Pull request by kcmin**
When Jerome approves a room reservation request for a room/time that has a conflict, there is no prompt indicating that there was a conflict, giving the impression that the request went through.

Please test it out to see if you guys can double book and whatnot, or if you guys try to put in something valid and it ends up failing.

### CODE REVIEW

**Comment by yipingbenjaminliu** [comment]
@kcmin, the clean method wasn't working for my test cases. I changed the logic a little and commented out the old code. Review it and test it and go from there.

**Comment by yipingbenjaminliu** [comment]
@kcmin, I tried submitting a RR that overlapped an existing reservation.
the following two cases were not working
image
image

**Comment by yipingbenjaminliu** [comment]
@kcmin, which test cases failed the current logic?

**Comment by kcmin** [comment]
@yipingbenjaminliu Benji, for both of those test cases, that is the expected outcome. 


Also from your logic, this failed for me:
image

**Comment by iamsitting** [comment]
Tested. Looks good. Let's return better feedback? Also doesn't account for Pending room reservations.

**Comment by iamsitting** [comment]
My bad didn't mean to delete gitignore. Will put back then merge.

**Pull request merged**
