### PR TITLE
Modifying HC survey report title.

### PR DESCRIPTION
**Pull request by bdou**

### CODE REVIEW

**Comment by francestsenn** [comment]
bitmoji

**Comment by joysyu** [comment]
IMG_1051 copy

**Comment by joysyu** [comment]
UNADJUSTEDNONRAW_thumb_1d1a

**Comment by jontey** [comment]
...

**Comment by francestsenn** [comment]
bitmoji @ryanli633

**Comment by yipingbenjaminliu** [comment]
what the...

**Comment by francestsenn** [comment]
bitmoji @bdou

**Pull request merged**
