### PR TITLE
Don't mark auto-graded exam as graded if it has essay questions

### PR DESCRIPTION
**Pull request by billyeh**
And still allow trainee to see immediate feedback for auto-grade. 

Addresses second point in #605

### CODE REVIEW

**Comment by ksungreborn** [comment]
We probably don't want trainees to be able to "VIEW GRADED RESPONSES" before they finish taking the exam right? The answers are on that view =)

**Comment by billyeh** [comment]
Yeah haha good point. I misread the if statements, just need to make sure they've finalized it too.

**Comment by ksungreborn** [comment]
Sorry, just noticed on my branch 'exams-test' the score for 'VIEW GRADED EXAM' looks correct, so I believe only on this branch it shows as '0' regardless of what score the trainee should've gotten.

**Comment by billyeh** [comment]
Works on my branch. We can see if it's reproducable later.

**Pull request merged**
