### PR TITLE
service reports

### PR DESCRIPTION
**Pull request by yipingbenjaminliu**
to address #788 and #787

### CODE REVIEW

**Comment by yipingbenjaminliu** [comment]
ready for testing, @ruthnan , @billyeh take a look and test it

**Comment by billyeh** [comment]
I'm not sure I want to take a look at this @ryanli633 and @jontey have been working on service scheduling though

**Comment by yipingbenjaminliu** [comment]
@billyeh , are they working on reports generation or mainly just the backend?

**Comment by billyeh** [comment]
They're working on the backend. #807 might have fixed the report though?

**Comment by yipingbenjaminliu** [comment]
yeeeee, i'ma close this PR then until this finish the backend

**Pull request closed without merging**
