### PR TITLE
Rolls Entry fix

### LINKED ISSUE #998: Roll, overarching issue
Duplicate rolls requires back-end fixes to ensure system handles duplicate rolls properly
attendance/rolls/{{event_type}} && attendance/rolls/
if trainee is on self attendance (trainee.self_attendance=True), only display rolls not submitted by the trainee and modify rolls that are not submitted by the trainee. eg: if Benji is on self attendance and he submits Tardy for a full min class, no one should be able to edit that roll from this page
if trainee is not on self attendance (trainee.self_attendance=True), then there should only be a unique roll and modify that unique roll, anyone should be able to modify that roll from this ba1ae37f3a25336c15cbef70c9a9ffa5818673d4

attendance/submit (aka personal attendance)
if trainee is on self attendance (trainee.self_attendance=True), only display rolls submitted by the trainee and modify rolls that are submitted by the trainee. eg: if Benji is on self attendance and he submits Tardy for a full min class, only he can edit that roll from this page
if trainee is not on self attendance (trainee.self_attendance=True), only display rolls not submitted by that trainee 5726e6b03370573eca1f4a3d5961e2d4452e447f

leaveslips
any submitted duplicate rolls where Roll.objects.filter(event, trainee, date).count() > 1 should be attached to the same leaveslip

SPECIAL CASE: from TA or AM view where they can switch to this trainee
if trainee is on self attendance, TA or AM should not be able to edit attendance rolls but they can finalize the attendance in that week/period
if trainee is not on self attendance, TA or AM should be able to edit attendance rolls and finalize the attendance in that week/period

### PR DESCRIPTION
**Pull request by yipingbenjaminliu**
#998

### CODE REVIEW

**Comment by yipingbenjaminliu** [comment]
@iamsitting ready for code review.

**Comment by yipingbenjaminliu** [comment]
@billyeh take it for a test run
try and run through possible scenarios involving trainees on self attendance or not, and with leaveslips or not.

**Comment by billyeh** [comment]
- trainee not on self attendance:
  - [x] AM rolls submitted appear correctly on table and self attendance with and without leave slip

**Comment by billyeh** [comment]
Tested a non-self attendance trainee and self-attendance trainee, everything displays correctly.

One issue is when a trainee finalizes attendance and comes in to office hours to change a roll, attendance monitors have no way of changing it on the frontend?

**Comment by ruthnan** [comment]
yup, it works for me, too. gj

**Pull request merged**
