### PR TITLE
Assign lifestudy fix

### PR DESCRIPTION
**Pull request by iamsitting**
Gave up. @yipingbenjaminliu

### CODE REVIEW

**Comment by iamsitting** [comment]
Okay. It works now. Buuutttt... it's super slow.

**Comment by billyeh** [comment]
😆 I remember trying to get it to run faster a few interims ago but I gave up

**Comment by yipingbenjaminliu** [comment]
@samvictor232 , also put in the dates for the period.

**Comment by xuefeizheng** [comment]
Sample Data

**Term 1:**
Angela W. 0
Phoebe C. 0

Angelo B. 0
Zion P. 0

**Term 2:** 

Tobi Adesoba 0
Jessica Chen 0

_Jesse Avila P3: 0 P4: 2_
Julius Chang 0

**Term 3:**

Rachel C. 0
Yang C. 0

Joseph H. 0
Kenny N. 0

**Term 4**

Basel 0
Jack J 0

Ruth Liang 0
Raven L: 0

**Comment by yipingbenjaminliu** [comment]
#1207

**Pull request closed without merging**
