### PR TITLE
Upgrade to Django 1.8

### PR DESCRIPTION
**Pull request by ricefield**
see #138 

Django 1.8 brings major upgrades to Django, most notably native Postgres support, some new data types, and native support for Jinja2. Full release notes here: https://docs.djangoproject.com/en/1.8/releases/1.8/

In addition, since we are upgrading from 1.6, we are getting all changes in Django 1.7 as well, most notably, native support for database migrations (this is big). Full release notes here: https://docs.djangoproject.com/en/1.7/releases/1.7/

This is a pretty big change. Again, upgrade instructions and troubleshooting is in #138. Props to @radicalray for getting this done.

### CODE REVIEW

**Comment by ricefield** [comment]
@radicalray I am getting a `django.db.utils.ProgrammingError: relation "absent_trainee_roster_roster_unreported_houses" already exists` even with `python manage.py migrate --fake-initial` can you troubleshoot?

@lifeunion @ysbecca @ludennis can you also try and get this working at some point?

**Comment by radicalray** [comment]
Tested for @haileyl and @snowboarder003, works. Merging.

**Comment by ricefield** [comment]
@radicalray please make sure this builds on a fresh install before merging. fixes like #145 will only work on the local machine, but it won't work on a fresh build. IIRC, we should remove coveralls(?) and update the version of django-extensions. I will try to get Travis working tonight so we have a reliable way to tests pull requests.

**Comment by radicalray** [comment]
I've tested on Ubuntu for fresh install. Works fine.

**Comment by ricefield** [comment]
@lifeunion I made some modifications to `.travis.yml` and `settings/travis.py`. Please take a look. Mainly I simplified the workflow, updated the build commands to be 1.8 appropriate, and took out the tests (because they are not working right now, I think). 

@radicalray now that TravisCI is reconfigured, we will use that as our standard. As you can see, there were still a few things that needed to be fixed. You didn't, by any chance, forget to push up some local commits, did you?

**Comment by radicalray** [comment]
Ok, merged all conflicts, updated travis, and fixed django 1.8 upgrade incompatibilities.

**Comment by ricefield** [comment]
awesome. thanks @radicalray :+1:

**Pull request merged**
