### PR TITLE
Models for HC Forms

### PR DESCRIPTION
**Pull request by iamsitting**
Models and Forms for HC Survey and HC Recommmendation.
Refer to issue #279

### CODE REVIEW

**Comment by iamsitting** [comment]
@yipingbenjaminliu The specs in #279 weren't super clear for HC forms. But this should be a good starting point. Let me know, if models need to be changed. I also added a populate_hc command to facilitate testing.

**Comment by yipingbenjaminliu** [comment]
@iamsitting , last thing for the hc survey
- make the name of the HC and the house an atuomated post, meaning when the HC presses submit, it should reflect the house and HC on the model, but the HC would have no option of changing his/her house and name

**Comment by yipingbenjaminliu** [comment]
need to add an option to add more than one line for HC recommendation.

**Comment by yipingbenjaminliu** [comment]
@iamsitting , tasks to do:

- confirm the admin.py so we can view the survey and recommendations in from localhost/admin
- have HC and and house field be an auto-fill upon submission and the average value by calculation
- HC survey submission returns a 302 error right now
- for the admin view for HC survey, show three items:
1)HC survey comments per house showing the HC user and the fields under HCGeneralComment
2)HC survey comments showing the HC user and the fields under HCTraineeComment
3)HC Recommendation showing all the fields under HCRecommendation

**Comment by yipingbenjaminliu** [comment]
had to remove some commits from other branches that I accidentally pushed into this. >< sorry peeps.

**Comment by iamsitting** [comment]
I don't think 302 is an error... just a redirect code? right?

**Comment by yipingbenjaminliu** [comment]
image
when i submit for a HC survey

**Comment by yipingbenjaminliu** [comment]
image

when i submit a HC recommendation

**Comment by iamsitting** [comment]
Fixed HC Survey submit. For HCRecommendations you probably need to manage.py makemigrations and migrate. It works fine for me. 😁

**Comment by yipingbenjaminliu** [comment]
fixes for HC survey:
- need a field called period (1-10 one period for two weeks), one possible entry per period
- period cannot be changed by HC but is automatic
- it seems that the current submitted HC survey cannot be recalled or edited by the HC
- if the period is the same, the HC should be able to go back in and edit it

changes for HC Recommendation:
- field changes to only three fields, trainee, yes/no (choice field), comment
- list every 2nd and 3rd term trainee along with their corresponding yes/no and comment
- HC should be able to edit it after submission

**Comment by ruthnan** [comment]
Is this one working, @iamsitting @yipingbenjaminliu?

**Comment by iamsitting** [comment]
Yes, working.

**Comment by billyeh** [comment]
A few files need to be deleted - `services_view.html` which probably came in from the merge, and the `jsoneditor` css and js files.

**Pull request merged**
