### PR TITLE
1144/rolls

### PR DESCRIPTION
**Pull request by yipingbenjaminliu**

### CODE REVIEW

**Comment by yipingbenjaminliu** [comment]
@ruthnan @priscilagonzalez , test it please.

**Comment by yipingbenjaminliu** [comment]
temp close, not yet ready.

**Comment by JoannaRumbley** [comment]
Can I ask what happened with this? I don't see changes on the live server... Made a comment on the issue #1144

**Comment by yipingbenjaminliu** [comment]
Code got too messy, decided to modularize the changes made, otherwise the code review would be a nightmare

**Pull request closed without merging**
