### PR TITLE
Upgrade select2

### PR DESCRIPTION
**Pull request by jontey**
Upgrading django-select2
Working on #478

### CODE REVIEW

**Comment by billyeh** [comment]
@schai6 You ran into the new version of django_selecte2 requesting select2 javascript from a CDN, right? 

That's what [the repo](https://github.com/applegrew/django-select2) says it does now. We'll have to see if we can change it to use some local assets (probably using the import from bundles/index.js since we already use it for the CSS), and tell it not to look for the assets online http://django-select2.readthedocs.io/en/latest/_modules/django_select2/conf.html?highlight=cdn

**Comment by jontey** [comment]
I think the problem with extending the select2 on jQuery is because django admin already loads a different version of jQuery. what we are extending is not $ but jQuery... i think the only way to deal with that would be to prevent django admin from loading their own jQuery and loading our own bundle

**Comment by billyeh** [comment]
You're right Jon. Works in 10e7448 in #521

**Comment by billyeh** [comment]
This is all mixed up with #521 now so gonna close.

**Pull request closed without merging**
