### PR TITLE
Page titles, Redesign

### PR DESCRIPTION
**Pull request by billyeh**
#245. With assortment of whitespace, unused files and views, and syllabus file cleanup.

Changed styles to reflect UI mockup (see https://www.dropbox.com/preview/attendance%20project/djattendance/Design%20-%20Miriam/Pages/Trainee%20Attendance_summary.png?role=personal)

Zero functionality changes.

### CODE REVIEW

**Comment by billyeh** [comment]
@skywalkerdude test

**Comment by ruthnan** [comment]
Who's you?

**Comment by billyeh** [comment]
Oh, originally I had Luke tagged in jest. I removed the tag though because the notifications from Github were getting annoying for him.

**Comment by billyeh** [comment]
@jontey this guy's ready for review 😄

**Pull request merged**
