### PR TITLE
Adding Celsius to TV Page need-spacing-and-font-sizing

### PR DESCRIPTION
**Pull request by zioninzion**
Help

#1768

### CODE REVIEW

**Comment by soaustin** [comment]
@zioninzion

**Comment by soaustin** [comment]
It's ready for review!

**Comment by zioninzion** [comment]
Screen Shot 2019-11-09 at 2 49 51 PM

**Comment by soaustin** [comment]
@zioninzion 
Screen Shot 2019-11-09 at 2 53 12 PM

**Comment by zioninzion** [comment]
Thank you, it's merged

**Pull request merged**
