### PR TITLE
add permission group named sister_training_assistant

### PR DESCRIPTION
**Pull request by davidhtien**

### CODE REVIEW

**Comment by yipingbenjaminliu** [comment]
@davidhtien , what's the reason for another group?

**Comment by davidhtien** [comment]
Mainly for ta detail view for leaveslips, right now the assign to another TA selector includes every TA including Saturday TAs and Brother Dennis etc, but if we just use the regular TA group it will exclude sister TAs which I believe is a wanted option in this case?

@JoannaRumbley @finben can you confirm?

**Comment by finben** [comment]
Yes, sister TA's are wanted

Am 13.06.2018 21:12 schrieb "David Tien" <notifications@github.com>:

Mainly for ta detail view for leaveslips, right now the assign to another
TA selector includes every TA including Saturday TAs and Brother Dennis
etc, but if we just use the regular TA group it will exclude sister TAs
which I believe is a wanted option in this case?

@JoannaRumbley <https://github.com/JoannaRumbley> @finben
<https://github.com/finben> can you confirm?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/attendanceproject/djattendance/pull/1209#issuecomment-397164832>,
or mute the thread

**Comment by yipingbenjaminliu** [comment]
is there a reason why we don't add sister TAs into the regular_training_assistant group?

**Pull request closed without merging**
