### PR TITLE
be able to unclick box

### PR DESCRIPTION
**Pull request by yipingbenjaminliu**
@ruthnan @priscilagonzalez @JoannaRumbley @finben 
this should allow trainees to unclick a box.

### CODE REVIEW

**Comment by billyeh** [comment]
Do these lines not already work? https://github.com/attendanceproject/djattendance/blob/5112c116844916160830dcb1efde883bb430b2ed/ap/bible_tracker/templates/bible_tracker/index.html#L292

If not, can we get rid of one, or if we need both because of different browser versions (?) just add them both closer to each other? I can un-click boxes on Chrome on my computer already on prod.

**Comment by yipingbenjaminliu** [comment]
huh, I thought the checked attribute was on label and not on the input... maybe I'm wrong.

**Comment by billyeh** [comment]
Sorry I didn't mark that issue I guess I didn't see it :)

**Comment by yipingbenjaminliu** [comment]
@billyeh, if it works on prod then it's good. Nevermind me. :P

**Comment by billyeh** [comment]
Ok. Yeah my bad I think I randomly fixed it a while ago and forgot to mark it.

**Comment by JoannaRumbley** [comment]
works on the live

**Pull request closed without merging**
