### PR TITLE
Designated services viewer

### PR DESCRIPTION
**Pull request by iamsitting**

### CODE REVIEW

**Comment by yipingbenjaminliu** [comment]
@iamsitting , are you done with this?

**Comment by billyeh** [comment]
The thing works, it's kind of more of a question of who's going to maintain it?

**Comment by yipingbenjaminliu** [comment]
Whichever weak AP trainee gets asked to do it in the future (2 Cor. 11:30)

**Comment by billyeh** [comment]
Looks good 😄 TAs said maintaining it is the service schedulers' job.

**Pull request merged**
