### PR TITLE
Automation: travis-saucelab test environments 

### PR DESCRIPTION
**Pull request by swenghj**

### CODE REVIEW

**Comment by billyeh** [comment]
👍

**Comment by swenghj** [comment]
Before starting test
1. make sure you have chrome(v60-62) or firefox(v54 or higher) web browser
2. make sure you have populated trainee and ta accounts and they are active, can login 

Run the test:
1. run the server locally(localhost:8000)
2. python [test name] -e [email address] -p [password] --taemail [ta email] --tapass [ta password] -d [driver]
        python web_access_request.py -e joon.jo@gmail.com -p *** -d chrome

**Comment by billyeh** [comment]
Looks good! @swenghj looks like we need a `data/WebAccessRequestsTest.json` file, right? That should be fine to commit to git since those are test results

**Comment by billyeh** [comment]
('assignment', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), default=[], size=None)),

**Comment by billyeh** [comment]
Passes on saucelab!

**Pull request merged**
