### PR TITLE
Service Hours Fix

### LINKED ISSUE #1075: Designated service hours hard to enter
- [x] When editing, the calendar function that pops up when selecting does not match the entered data but defaults to the current date. (Could not replicate - @iamsitting)
- [x] Military time is not intuitive. #1079 
- [x] Upon saving, the chronological ordering disappears. #1079 
- [x] Exception Type: MultipleObjectsReturned at /services/service_hours_ta_view
Exception Value: get() returned more than one ServiceAttendance -- it returned 2! 1af8060f6a4201b28f1c0007ae7d92470168acbb

### PR DESCRIPTION
**Pull request by iamsitting**
#1075 
1. Fixed service hours chron order
2. 24 hr to 12 hr time

### CODE REVIEW

**Comment by iamsitting** [comment]
@yipingbenjaminliu review?

**Comment by iamsitting** [comment]
@yipingbenjaminliu i couldn't get that on safari and firefox. Try again with latest commit.

**Comment by yipingbenjaminliu** [comment]
it's on chrome

**Comment by yipingbenjaminliu** [comment]
time reverts and hour.

**Comment by yipingbenjaminliu** [comment]
screenshot from 2018-04-26 13-46-13
screenshot from 2018-04-26 13-46-16
upon submit, it throws an unknown string format

**Comment by yipingbenjaminliu** [comment]
@ruthnan ready for testing

**Comment by yipingbenjaminliu** [comment]
@iamsitting ready for testing?

**Pull request merged**
